### ISSUE TITLE
Cannot restart, stop and debug individual resources on MacOS Sequoia

### ISSUE THREAD

**Issue by OliverRC** [JetBrains/aspire-plugin#336]
**Describe the bug**

**To Reproduce**
Steps to reproduce the behaviour:
1. Open dotnet aspire sln on MacOS
2. Run a Aspire run/debug configuration
3. Go to services
4. Select a resource

None of the services can be restarted, stopped or restarted in debug mode.
One has to restart the entire aspire host for any change.

**Expected behaviour**
Previously on my Windows 11 machine I could restart, and debug individual resources

**Screenshots**

![Image](https://github.com/user-attachments/assets/85c57ad7-814d-4049-bed8-9a9b0890f7f0)

**System information:**
 - OS: MacOS Sequoia 15.1.1
 - .NET version: 9.0.100
 - JetBrains Rider version: 2024.3.3
 - Aspire plugin version: 1.6.4 (bundled ... cannot upgrade)
 - Aspire workload version: 8.2.2/8.0.100

**Comment by rafaelldi** [comment]
As far as I remember, it is related to the `http` profile, but I need to check it again

**Comment by OliverRC** [comment]
Created a YouTrack issue on to maybe JetBrains can comment: https://youtrack.jetbrains.com/issue/RIDER-122173/Cannot-restart-stop-and-debug-individual-resources-on-MacOS-Sequoia

**Comment by rafaelldi** [comment]
You do not need to duplicate issues. Issues on YouTrack don't have a higher priority or anything. On the contrary, managing duplicates becomes more difficult.

**Comment by OliverRC** [comment]
Okay cool, which platform do you prefer? I can close out the other issue.

**Comment by rafaelldi** [comment]
Let's use the GitHub's one

**Comment by rafaelldi** [comment]
I changed the internal architecture, so I think that might help. At least I can no longer reproduce the error after the changes.

**Comment by rafaelldi** [comment]
@OliverRC It should be fixed only with 1.7.* versions of the plugin and Rider 2025.1

**Comment by OliverRC** [comment]
Why is this plugin bundled and therefore directly tied to Rider releases? This significantly reduces the cadence of updates and doesn't allow fixes to the plugin to make their way to customers quickly. Its odd as it's an exception to how most other plugins are released.

**Comment by OliverRC** [comment]
I have tried in Rider 2025.1 EAP 7 with Aspire 1.7.7 and it still does not work

**Comment by OliverRC** [comment]
Please can this be reopened as it does not look to be resolved.

**Comment by rafaelldi** [comment]
@OliverRC I've reopened your YouTrack ticket. Could you please enable the Aspire trace scenarios (via Help | Diagnostic Tools | Choose Trace Scenarios | Aspire), reproduce the issue, collect logs (via Help | Collect Logs and Diagnostic Data) and attach them to the YouTrack issue? You can set appropriate visibility for the logs (e.g. for `jetbrains-team`). I'll take a look.
